on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Installiere Perl Module und Postgresql
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib libtest-deep-perl libtest-exception-perl libtest-output-perl libwww-perl liburi-find-perl libsys-cpu-perl libthread-pool-simple-perl libdbd-pg-perl libdbi-perl      
      - name: Configurieren
        run: |
          cp config/kivitendo.conf.default config/kivitendo.conf
          sed -i '/db[ ]*=/ s/$/ testdb/' config/kivitendo.conf
          sudo sed -i '/host[ ]*all[ ]*all[ ]*127/s/scram-sha-256/trust/' /etc/postgresql/14/main/pg_hba.conf
      - name: Postgresql starten
        run: sudo service postgresql start
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Starten der Tests...
        run: t/test.pl
